url: "https://www.pythonbits.de" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: "PythonBits" # the name of your site, e.g. ACME Corp.
lang: de

permalink: /:categories/:title:output_ext